# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 23:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth0User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth0_id', models.CharField(max_length=90)),
                ('name', models.CharField(blank=True, max_length=90, null=True)),
                ('email', models.CharField(blank=True, max_length=90, null=True)),
                ('picture', models.CharField(blank=True, max_length=90, null=True)),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
