# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 10:46
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth0user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auth0user',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
