# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account_manager', '0002_auto_20161118_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth0user',
            name='picture',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
