# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 10:53
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account_manager', '0003_auto_20161118_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth0user',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name'),
        ),
    ]
