# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0005_auto_20161124_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth0user',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
