# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('other_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
