# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scene_manager', '0002_analysis_locked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='user',
            new_name='owner',
        ),
    ]
