# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scene_manager', '0004_auto_20161111_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='filters',
        ),
    ]
