# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 16:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account_manager', '0001_initial'),
        ('scene_manager', '0006_auto_20161117_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scene_manager.Analysis')),
                (
                'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_manager.Auth0User')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default='name', max_length=40),
            preserve_default=False,
        ),
    ]
