# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scene_manager', '0007_auto_20161117_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='is_question',
            field=models.BooleanField(default=False),
        ),
    ]
