# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-19 11:15
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scene_manager', '0008_scene_is_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='scene',
            name='is_question',
        ),
        migrations.AddField(
            model_name='scene',
            name='status',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE,
                                    to='scene_manager.SceneStatus'),
            preserve_default=False,
        ),
    ]
