# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 11:44
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scene_manager', '0010_auto_20161119_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='temp', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
