# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 17:38
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scene_manager', '0012_auto_20161124_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True),
        ),
    ]
