# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scene_manager', '0013_auto_20161124_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
