# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 13:08
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('scene_manager', '0014_analysis_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='scene_manager.SceneStatus'),
        ),
    ]
