# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 14:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scene_manager', '0015_auto_20161125_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='slug', editable=False,
                                                populate_from='name', unique_with=('analysis',)),
            preserve_default=False,
        ),
    ]
