# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 15:49
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('scene_manager', '0018_auto_20161125_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name',
                                                unique_with=('analysis',)),
        ),
    ]
