# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scene_manager', '0020_auto_20161125_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scene_manager.Video'),
        ),
    ]
