# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 20:19
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scene_manager', '0022_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique_with=('scene',)),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique_with=('analysis', 'camera')),
        ),
    ]
