# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 23:01
from __future__ import unicode_literals

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models

import inskop.code_manager.models
import inskop.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('account_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, storage=inskop.storage.OverwriteStorage(),
                                          upload_to=inskop.code_manager.models.code_path)),
                ('default_param', models.CharField(max_length=400, null=True)),
                ('read_me', models.TextField(blank=True, null=True)),
                ('valid', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_manager.Code')),
                (
                'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_manager.Auth0User')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('param', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('code',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='code_manager.Code')),
                ('owner',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_manager.Auth0User')),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='code_manager.CodeCategory'),
        ),
        migrations.AddField(
            model_name='code',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_manager.Auth0User'),
        ),
    ]
