# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('code_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='default_param',
        ),
    ]
