# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('code_manager', '0002_remove_code_default_param'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='name',
        ),
        migrations.AddField(
            model_name='code',
            name='default_param',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
