# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 17:38
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('code_manager', '0003_auto_20161115_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True),
        ),
    ]
