# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 13:52
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_manager', '0004_auto_20161124_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='code',
        ),
        migrations.RemoveField(
            model_name='process',
            name='param',
        ),
        migrations.AddField(
            model_name='process',
            name='name',
            field=models.CharField(default='orig', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='process',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default='orig', editable=False, populate_from='name', unique=True),
            preserve_default=False,
        ),
    ]
